# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "golang-tutorial"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20131103.box"

  config.vm.hostname = "golang-tutorial"

  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.synced_folder "../..", "/home/vagrant/gotutorial/src/github.com/cmceniry/gotutorial", create: true

  config.vm.provision "shell", inline: <<SHELL

# Install GO
echo Installing GO
curl -o /tmp/go1.3.linux-amd64.tar.gz https://storage.googleapis.com/golang/go1.3.linux-amd64.tar.gz
rm -rf /usr/local/go
tar -C /usr/local -zxf /tmp/go1.3.linux-amd64.tar.gz
cat > /home/vagrant/.gotutorialrc <<EOF
GOROOT=/usr/local/go
GOPATH=/home/vagrant/gotutorial
PATH=\\\${PATH}:\\\${GOROOT}/bin

export GOROOT GOPATH PATH
EOF
chown vagrant:vagrant /home/vagrant/.gotutorialrc
echo ". ~/.gotutorialrc" >> /home/vagrant/.bashrc

# Installing ASM
echo Installing OracleASM
curl -o /etc/yum.repos.d/public-yum-ol6.repo http://public-yum.oracle.com/public-yum-ol6.repo
curl -o /etc/pki/rpm-gpg/RPM-GPG-KEY-oracle http://public-yum.oracle.com/RPM-GPG-KEY-oracle-ol6
yum --disablerepo=* --enablerepo=ol6_latest install -y kmod-oracleasm oracleasm-support
sed -ie 's/^ORACLEASM_ENABLED=.*/ORACLEASM_ENABLED=true/;' /etc/sysconfig/oracleasm
/sbin/chkconfig oracleasm on
/etc/init.d/oracleasm start

# Setting up ASM Disks
echo Setting up OracleASM disks
mkdir /var/asmdisks
dd if=/dev/zero of=/var/asmdisks/d1 bs=1024 count=10240
losetup /dev/loop1 /var/asmdisks/d1
/etc/init.d/oracleasm createdisk ASMDISK1 /dev/loop1
dd if=/dev/zero of=/var/asmdisks/d2 bs=1024 count=10240
losetup /dev/loop2 /var/asmdisks/d2
/etc/init.d/oracleasm createdisk ASMDISK2 /dev/loop2
dd if=/dev/zero of=/var/asmdisks/d3 bs=1024 count=10240
losetup /dev/loop3 /var/asmdisks/d3
/etc/init.d/oracleasm createdisk ASMDISK3 /dev/loop3
dd if=/dev/zero of=/var/asmdisks/d4 bs=1024 count=10240
losetup /dev/loop4 /var/asmdisks/d4
/etc/init.d/oracleasm createdisk ASMDISK4 /dev/loop4
/etc/init.d/oracleasm listdisks

# Setup sysstat
echo Installing sysstat
yum install -y sysstat

# Fixing permissions
chown -R vagrant:vagrant /home/vagrant

# Setting motd
cat > /etc/motd <<EOF
Welcome to the Go for System Tools exercises

"cd gotutorial" to get started
EOF

SHELL

  #config.vm.provision "puppet" do |puppet|
    #puppet.manifests_path = "."
    #puppet.manifest_file = "manifest.pp"
  #end

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network :forwarded_port, guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network :private_network, ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file base.pp in the manifests_path directory.
  #
  # An example Puppet manifest to provision the message of the day:
  #
  # # group { "puppet":
  # #   ensure => "present",
  # # }
  # #
  # # File { owner => 0, group => 0, mode => 0644 }
  # #
  # # file { '/etc/motd':
  # #   content => "Welcome to your Vagrant-built virtual machine!
  # #               Managed by Puppet.\n"
  # # }
  #
  # config.vm.provision :puppet do |puppet|
  #   puppet.manifests_path = "manifests"
  #   puppet.manifest_file  = "site.pp"
  # end

  # Enable provisioning with chef solo, specifying a cookbooks path, roles
  # path, and data_bags path (all relative to this Vagrantfile), and adding
  # some recipes and/or roles.
  #
  # config.vm.provision :chef_solo do |chef|
  #   chef.cookbooks_path = "../my-recipes/cookbooks"
  #   chef.roles_path = "../my-recipes/roles"
  #   chef.data_bags_path = "../my-recipes/data_bags"
  #   chef.add_recipe "mysql"
  #   chef.add_role "web"
  #
  #   # You may also specify custom JSON attributes:
  #   chef.json = { :mysql_password => "foo" }
  # end

  # Enable provisioning with chef server, specifying the chef server URL,
  # and the path to the validation key (relative to this Vagrantfile).
  #
  # The Opscode Platform uses HTTPS. Substitute your organization for
  # ORGNAME in the URL and validation key.
  #
  # If you have your own Chef Server, use the appropriate URL, which may be
  # HTTP instead of HTTPS depending on your configuration. Also change the
  # validation key to validation.pem.
  #
  # config.vm.provision :chef_client do |chef|
  #   chef.chef_server_url = "https://api.opscode.com/organizations/ORGNAME"
  #   chef.validation_key_path = "ORGNAME-validator.pem"
  # end
  #
  # If you're using the Opscode platform, your validator client is
  # ORGNAME-validator, replacing ORGNAME with your organization name.
  #
  # If you have your own Chef Server, the default validation client name is
  # chef-validator, unless you changed the configuration.
  #
  #   chef.validation_client_name = "ORGNAME-validator"
end
